# 5 Interesting Tensor Functions In PyTorch!

### In this notebook i will be talking about these 5 **COOL** functions in [PyTorch](http://www.pytorch.org) -->


>##### 1. `torch.eye()`
>##### 2. `torch.unique()`
>##### 3. `tensor.new_tensor()`
>##### 4. `tolist()`
>##### 5. `torch.ge()`

In [2]:
#Importing all the necessary stuff....
import torch

### 1.` torch.eye()`

#### So, i am going to begin with `torch.eye()` which is a nice function in torch.
First of all..if you dont know about an identity matrix, Its a matrix which has 1 filled at it's diagonal and 0 everywhere else. Let me give you an example!

$ I_{3} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} $

$I_{3}$ is an Identity matrix of order 3.


 Basically what torch.eye() *does* is that it creates an Identity Matrix (Tensor) of the order you specify. `torch.eye(n)` takes a parameter n which is an integer!

In [29]:
#Example-1
myTensor = torch.eye(3)
myTensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

So let's check the shape of the tensor!

In [30]:
#Shape Check
myTensor.shape

torch.Size([3, 3])

So, as it can be clearly seen..`torch.eye()` returns a 2-D tensor.

Now, `torch.eye(n,m)` can also take an optional argument m which specifies that how many columns you want to have in the matrix (or the tensor)

**NOTE:**  The second parameter does not change the Identity matrix order, It just changes the number of columns in the tensor(matrix). It would be more clear with the example below!

In [26]:
#Example-2
myTensor2 = torch.eye(3,4)
myTensor2

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [32]:
#Example-3
myTensor3 = torch.eye(3,5)
myTensor3

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

Also the datatype could be changed using `dtype`

In [35]:
#Example-4
myTensor4 = torch.eye(4,dtype=torch.int32)

myTensor4

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]], dtype=torch.int32)

Now, as i said `torch.eye(n)` takes n as an argument which must be an integer. It would return an error if a float is passes as an argument. Lets have a **LOOK**!

In [36]:
#Breaks..
myTensor5 =torch.eye(4.)

TypeError: eye(): argument 'n' (position 1) must be int, not float

### 2. `torch.unique()`

#### So, the next function which i will be talking about is simple yet interesting!

So I hope that you all must be familiar with Sets in Mathematics.\
$\{1,2,3\}$ is a set!

Also there are sets in python!\
`{1,2,3}`

Sets can't have a value repeated more than once...\
For example --> $\{1,2,3,2\}$ is not a **SET**! as the integer 2 comes ~~once~~ *twice*!

In [108]:
#Observe how python set contains only the unique elements!
pyset = {1,2,3,3,4,1,1,2}
pyset

{1, 2, 3, 4}

Similarly, `torch.unique()` returns the unique elements in a tensor! 

In [106]:
#Example-2
myTensor6 = torch.tensor([1,2,3,4,4,5,2,4])
torch.unique(myTensor6)

tensor([1, 2, 3, 4, 5])

As i said the function is very simple!
* `torch.unique()` can take multi dimenional tensors also!


In [120]:
#Example-3..
myTensor7 = torch.tensor([[[1,2,3],[1,2,3]],[[1,2,3],[4,4,5]]])
torch.unique(myTensor7)

tensor([1, 2, 3, 4, 5])

### 3.`tensor.new_tensor()`

#### The $3^{rd}$ function is a function not related to torch...instead related to tensor!

Ever wondered how to convert a simple list(or an array like object) into a tensor?\
`tensorName.new_tensor(n)` is the Solution!

This function takes an argument which must be an array_like object.

The argument can be =>
* A list
* A tuple

In [123]:
#Example-1
myList = [1,2,3,4,5]
myTensor8 = tensor.new_tensor(myList)
myTensor8

tensor([1, 2, 3, 4, 5])

This function can also take a nested list in order to make multi-dimensional tensors!

In [124]:
#Example-2
myList2 = [[1,2,3],[4,5,6]]
myTensor9 = tensor.new_tensor(myList2)
myTensor9

tensor([[1, 2, 3],
        [4, 5, 6]])

Now lets try out this functions with tupple!

In [155]:
#Example-3
myTupple = (1,2,3,4,5)
myTupple2 = ((1,2,3),(3,4,5))

myTensor10 = tensor.new_tensor(myTupple)
myTensor11 = tensor.new_tensor(myTupple2)

print("With Tupple -->")
print(myTensor10)
print("-"*100)
print("With Tupple(nested) -->")
print(myTensor11)

With Tupple -->
tensor([1, 2, 3, 4, 5])
----------------------------------------------------------------------------------------------------
With Tupple(nested) -->
tensor([[1, 2, 3],
        [3, 4, 5]])


This function is also valid when you pass internested lists and tupple! 

In [156]:
#Example-4
myList3 = [(1,2),(2,3)]
myTupple3 = ([1,2,3],[4,5,6])
myList4 = [(1,2),[3,4]]

myTensor12 = tensor.new_tensor(myList3)
myTensor13 = tensor.new_tensor(myTupple3)
myTensor14 = tensor.new_tensor(myList4)

print("Tupple in List -->")
print(myTensor12)
print("-"*100)
print("List in Tupple -->")
print(myTensor13)
print("-"*100)
print("Tupple and List in Tupple -->")
print(myTensor14)

Tupple in List -->
tensor([[1, 2],
        [2, 3]])
----------------------------------------------------------------------------------------------------
List in Tupple -->
tensor([[1, 2, 3],
        [4, 5, 6]])
----------------------------------------------------------------------------------------------------
Tupple and List in Tupple -->
tensor([[1, 2],
        [3, 4]])


**NOTE:This function is not valid if the argument is a set.**\
Lets test it out!

In [157]:
#breaks..
mySet = {1,2,3}
myTensor15 = tensor.new_tensor(mySet)
myTensor15

TypeError: an integer is required (got type set)

### 4.`tolist()`

#### Now, here i have the $4^{th}$ function related to tensors!

This function is just like the opposite of the $3^{rd}$ function which was `new_tensor()`\
`tensor.tolist()` returns a list! 

In [173]:
#Example-1
myTensor16 = torch.tensor([1,2,3,4,5])
print("The Tensor -->")
print(myTensor16)

print("-"*100)

theList = myTensor16.tolist()
print("Tensor to List -->")
print(theList)

The Tensor -->
tensor([1, 2, 3, 4, 5])
----------------------------------------------------------------------------------------------------
Tensor to List -->
[1, 2, 3, 4, 5]


`tensor.tolist()` can also work with a multi dimensional tensor by returning a nested list!

In [174]:
#Example-2
myTensor17 = torch.randn(2,3)
print("The Tensor -->")
print(myTensor17)

print("-"*100)

theList2 = myTensor17.tolist()
print("Tensor to Nested List -->")
print(theList2)

The Tensor -->
tensor([[ 0.6395, -0.4398, -0.0324],
        [ 0.4730, -0.8334,  1.1056]])
----------------------------------------------------------------------------------------------------
Tensor to Nested List -->
[[0.6394500732421875, -0.4398006200790405, -0.03236221522092819], [0.47296205163002014, -0.8333988785743713, 1.105611801147461]]


### 5.`torch.ge()`

#### So, here i come to the last but not the least function of this notebook!

This function compares two tensors with each other or a tensor to a scalar and returns a tensor consisting of type boolean!

$Tensor =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$
 
 `torch.ge(Tensor,1)` compares every element of Tensor matrix to the scalar argument according to the equation --> 
 > $a_{m,n} \geq scalar$



In [188]:
#Example-1
myTensor18 = torch.tensor([[1,2,5,4],[12,5,2,4]])
theBool = torch.ge(myTensor18,5)
theBool

tensor([[False, False,  True, False],
        [ True,  True, False, False]])

Now lets try `torch.ge()` to compare two tensors!

In [189]:
#Example-2
myTensor19 = torch.tensor([[1,6,4,2],[5,3,2,6]])
myTensor20 = torch.tensor([[2,6,3,1],[6,4,2,3]])

theBool2 = torch.ge(myTensor19,myTensor20)
theBool2

tensor([[False,  True,  True,  True],
        [False, False,  True,  True]])